[package]
name = "madara-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "madara"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
dirs = "5.0.1"
git2 = "0.18.1"
inquire = "0.6.2"
log = "0.4.20"
remove_dir_all = "0.8.2"
reqwest = { version = "0.11.23", features = ["json", "blocking"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.109"
strum = { version = "0.25.0", features = ["derive"] }
strum_macros = { version = "0.25.3", features = [] }
thiserror = "1.0.52"
toml = "0.8.8"
config = "0.13.4"
env_logger = "0.10.1"
